{
 "title": "Acme",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Acme Orders Posts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{method=\"POST\",job=\"acme\",controller=\"Orders\"}[15s])",
     "legendFormat": "Status Code: {{code}}"
    }
   ]
  },
  {
   "title": "Current Stock Levels",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "product_stock_levels", "legendFormat": "{{product}}" }
   ]
  },
  {
   "title": "Acme Stock Levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "product_stock_levels", "legendFormat": "{{product}}" }
   ]
  },
  {
   "title": "Total Stock",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "product_stock_levels", "legendFormat": "{{product}}" }
   ]
  },
  {
   "title": "Acme 95% Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"acme\"}[5m])) by (le))"
    }
   ]
  }
 ]
}