global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus

    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
