apiVersion: v1

kind: Pod

metadata:
  name: prometheus
spec:
  containers:
    - image: prom/prometheus
      name: prometheus
      ports:
        - containerPort: 9090
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"
      volumeMounts:
        - mountPath: /prometheus
          name: tsdb-storage
        - mountPath: /etc/prometheus
          name: config

  volumes:
    - name: tsdb-storage
      emptyDir: {}
    - name: config
      configMap:
        name: prometheus-config
