apiVersion: v1

kind: Pod

metadata:
  name: dotnetsample
spec:
  containers:
    - image: jamesworld/monitoring-dotnetsample:1.0
      name: dotnetsample
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"
