apiVersion: v1

kind: Pod

metadata:
  name: dotnetsample
  annotations:
    prometheus.io/scrape: "true"
spec:
  containers:
    - image: jamesworld/monitoring-dotnetsample:1.0
      name: dotnetsample
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"

      env:
        - name: KUBE_ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
